export const GET_ALL_ASSEMBLY_PO_REQUEST = "GET_ALL_ASSEMBLY_PO_REQUEST";
export const GET_ALL_ASSEMBLY_PO_SUCCESS = "GET_ALL_ASSEMBLY_PO_SUCCESS";
export const GET_ALL_ASSEMBLY_PO_FAILURE = "GET_ALL_ASSEMBLY_PO_FAILURE";

export const UPDATE_ASSEMBLY_PO_REQUEST = "UPDATE_ASSEMBLY_PO_REQUEST";
export const UPDATE_ASSEMBLY_PO_SUCCESS = "UPDATE_ASSEMBLY_PO_SUCCESS";
export const UPDATE_ASSEMBLY_PO_FAILURE = "UPDATE_ASSEMBLY_PO_FAILURE";

export const GET_ALL_ASSEMBLY_PO_BY_ID_REQUEST = "GET_ALL_ASSEMBLY_PO_BY_ID_REQUEST";
export const GET_ALL_ASSEMBLY_PO_BY_ID_SUCCESS = "GET_ALL_ASSEMBLY_PO_BY_ID_SUCCESS";
export const GET_ALL_ASSEMBLY_PO_BY_ID_FAILURE = "GET_ALL_ASSEMBLY_PO_BY_ID_FAILURE";