export const GET_ALL_BULK_RAW_MATERIAL_PO_REQUEST = "GET_ALL_BULK_RAW_MATERIAL_PO_REQUEST";
export const GET_ALL_BULK_RAW_MATERIAL_PO_SUCCESS = "GET_ALL_BULK_RAW_MATERIAL_PO_SUCCESS";
export const GET_ALL_BULK_RAW_MATERIAL_PO_FAILURE = "GET_ALL_BULK_RAW_MATERIAL_PO_FAILURE";

export const UPDATE_BULK_RAW_MATERIAL_PO_REQUEST = "UPDATE_BULK_RAW_MATERIAL_PO_REQUEST";
export const UPDATE_BULK_RAW_MATERIAL_PO_SUCCESS = "UPDATE_BULK_RAW_MATERIAL_PO_SUCCESS";
export const UPDATE_BULK_RAW_MATERIAL_PO_FAILURE = "UPDATE_BULK_RAW_MATERIAL_PO_FAILURE";
