export const GET_CATEGORY_VALUE = "GET_CATEGORY_VALUE";
export const GET_MATERIAL_VALUE = "GET_MATERIAL_VALUE";
export const GET_MATERIAL_NAME = "GET_MATERIAL_NAME";
export const GET_VENDOR_VALUE = "GET_VENDOR_VALUE";
export const GET_PRODUCT_VALUE = "GET_PRODUCT_VALUE";
export const GET_BATCH_NUMBER = "GET_BATCH_NUMBER";
export const GET_PRODUCT_NAME = "GET_PRODUCT_NAME";
