export const GET_ALL_INVENTORY_PO_REQUEST = "GET_ALL_INVENTORY_PO_REQUEST";
export const GET_ALL_INVENTORY_PO_SUCCESS = "GET_ALL_INVENTORY_PO_SUCCESS";
export const GET_ALL_INVENTORY_PO_FAILURE = "GET_ALL_INVENTORY_PO_FAILURE";

export const GET_INVENTORY_POBYID_REQUEST = "GET_INVENTORY_POBYID_REQUEST";
export const GET_INVENTORY_POBYID_SUCCESS = "GET_INVENTORY_POBYID_SUCCESS";
export const GET_INVENTORY_POBYID_FAILURE = "GET_INVENTORY_POBYID_FAILURE";

export const UPDATE_INVENTORY_PO_REQUEST = "UPDATE_INVENTORY_PO_REQUEST";
export const UPDATE_INVENTORY_PO_SUCCESS = "UPDATE_INVENTORY_PO_SUCCESS";
export const UPDATE_INVENTORY_PO_FAILURE = "UPDATE_INVENTORY_PO_FAILURE";
