//means get all orders
export const GET_ALL_AMAZON_ORDERS_REQUEST = "GET_ALL_AMAZON_ORDERS_REQUEST";
export const GET_ALL_AMAZON_ORDERS_SUCCESS = "GET_ALL_AMAZON_ORDERS_SUCCESS";
export const GET_ALL_AMAZON_ORDERS_FAILURE = "GET_ALL_AMAZON_ORDERS_FAILURE";

//means get all orders
export const GET_ALL_CUSTOM_ORDERS_REQUEST = "GET_ALL_CUSTOM_ORDERS_REQUEST";
export const GET_ALL_CUSTOM_ORDERS_SUCCESS = "GET_ALL_CUSTOM_ORDERS_SUCCESS";
export const GET_ALL_CUSTOM_ORDERS_FAILURE = "GET_ALL_CUSTOM_ORDERS_FAILURE";

export const GET_ORDERBY_ORDERID_REQUEST = "GET_ORDERBY_ORDERID_REQUEST";
export const GET_ORDERBY_ORDERID_SUCCESS = "GET_ORDERBY_ORDERID_SUCCESS";
export const GET_ORDERBY_ORDERID_FAILURE = "GET_ORDERBY_ORDERID_FAILURE";

export const GET_ALL_OPEN_ORDERS_REQUEST = "GET_ALL_OPEN_ORDERS_REQUEST";
export const GET_ALL_OPEN_ORDERS_SUCCESS = "GET_ALL_OPEN_ORDERS_SUCCESS";
export const GET_ALL_OPEN_ORDERS_FAILURE = "GET_ALL_OPEN_ORDERS_FAILURE";
