export const GET_ALL_PICKLIST_REQUEST = "GET_ALL_PICKLIST_REQUEST";
export const GET_ALL_PICKLIST_SUCCESS = "GET_ALL_PICKLIST_SUCCESS";
export const GET_ALL_PICKLIST_FAILURE = "GET_ALL_PICKLIST_FAILURE";

export const GET_PICKLIST_BYID_REQUEST = "GET_PICKLIST_BYID_REQUEST";
export const GET_PICKLIST_BYID_SUCCESS = "GET_PICKLIST_BYID_SUCCESS";
export const GET_PICKLIST_BYID_FAILURE = "GET_PICKLIST_BYID_FAILURE";
