export const GET_ALL_PRODUCT_REQUEST = 'GET_ALL_PRODUCT_REQUEST';
export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS';
export const GET_ALL_PRODUCT_FAILURE = 'GET_ALL_PRODUCT_FAILURE';

export const GET_ALL_PRODUCT_BYCATEID_REQUEST =
  'GET_ALL_PRODUCT_BYCATEID_REQUEST';
export const GET_ALL_PRODUCT_BYCATEID_SUCCESS =
  'GET_ALL_PRODUCT_BYCATEID_SUCCESS';
export const GET_ALL_PRODUCT_BYCATEID_FAILURE =
  'GET_ALL_PRODUCT_BYCATEID_FAILURE';

export const GET_PRODUCT_BYID_REQUEST = 'GET_PRODUCT_BYID_REQUEST';
export const GET_PRODUCT_BYID_SUCCESS = 'GET_PRODUCT_BYID_SUCCESS';
export const GET_PRODUCT_BYID_FAILURE = 'GET_PRODUCT_BYID_FAILURE';
