export const GET_ALL_RTO_ORDER_REQUEST = "GET_ALL_RTO_ORDER_REQUEST";
export const GET_ALL_RTO_ORDER_SUCCESS = "GET_ALL_RTO_ORDER_SUCCESS";
export const GET_ALL_RTO_ORDER_FAILURE = "GET_ALL_RTO_ORDER_FAILURE";